apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    # Prevents the onboarding pipeline from being created when the component is created.
    build.appstudio.openshift.io/status: '{"pac":{"state":"enabled"},"message":"done"}'
  name: package-name
spec:
  application: calunga-lucarval-test
  componentName: package-name
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/package-name
  source:
    git:
      dockerfileUrl: Containerfile
      url: https://github.com/lcarva/wheel-build-task-test.git
