apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/application: calunga-lucarval-test
    appstudio.redhat.com/component: package-name
  name: package-name
spec:
  image:
    name: tenant/package-name
    visibility: public
  notifications:
  - config:
      url: https://bombino.api.redhat.com/v1/sbom/quay/push
    event: repo_push
    method: webhook
    title: SBOM-event-to-Bombino
