FROM registry.redhat.io/ubi9/python-312:latest

USER root
RUN dnf install -y cmake

USER 1001
# TODO: Remove the pulp-cli wheel once an image exists:
# https://github.com/pulp/pulp-oci-images/issues/744
RUN pip install build wheel pulp-cli
