---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/lcarva/wheel-build-task-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[packages/werkzeug/**]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: calunga-lucarval-test
    appstudio.openshift.io/component: werkzeug-lucarval-test
    pipelines.appstudio.openshift.io/type: build
  name: werkzeug-on-pull-request
  namespace: calunga-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/calunga-tenant/werkzeug-lucarval-test:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: path-context
    value: packages/werkzeug
  - name: dockerfile
    value: Containerfile
  - name: build-args-file
    value: packages/werkzeug/argfile.conf
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: |
      {
        "type": "pip",
        "path": "./packages/werkzeug",
        "allow_binary": "false"
      }
  pipelineRef:
    name: build
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
